### ISSUE TITLE
smoke test on host ?

### ISSUE THREAD

**Issue by ajlennon** [foundriesio/fiotest#11]
Hi there,

Just want to say I LOVE the fiotest stuff. Having put together a few scriptable test frameworks for board QA and information capture over the years this looks to be JUST what we need, and I'm so pleased I don't have to do it :)

One thing that I've been fighting with today though. I couldn't get my custom script working when I copied your smoke test script setup and having now found and read through the articles I and II (perhaps add these to the README?) I see it's because the use_host actually runs the test on the host, and the Dockerfile is copying the script into the container, so shouldn't this be false? Or am I missing something?

https://github.com/foundriesio/fiotest/blob/cea30be53a79536a6d4e82df43e657dc8c58a8d5/test-spec.yml#L17

Cheers!

Alex

**Comment by doanac** [comment]
Hey Alex - long time no see :). You are correct this is a broken example. I've put a PR for this

 https://github.com/foundriesio/fiotest/pull/12

**Comment by ajlennon** [comment]
Brillo @doanac. Hope all's well with you sir!
