### ISSUE TITLE
fiotest container never exits / port 8000 exposed on local network

### ISSUE THREAD

**Issue by ajlennon** [foundriesio/fiotest#13]
Hi there,

Getting to grips with fiotest here... The test spec seems to run then sit forever rather than the container exit.

Is this the expected behaviour? Or is there a way to free up the container when the tests have executed?

Thanks!

Alex

**Comment by doanac** [comment]
The idea is that we run the tests every time a new target is deployed. So its running as a daemon:

 https://github.com/foundriesio/fiotest/blob/master/docker-compose.yml#L8

that aklite notifies after each install operation.

**Comment by ajlennon** [comment]
The wider issue we've come across here is that the `docker-compose.yml` in your example EXPOSEs port 8000 on the local network.

I see I can EXPOSE this only on localhost so will shoot up a PR for consideration

**Comment by ajlennon** [comment]
ref: https://github.com/foundriesio/fiotest/pull/15

**Comment by ajlennon** [comment]
Thanks @doanac will close this down then
