### ISSUE TITLE
Super user privileges for a test - best practice?

### ISSUE THREAD

**Issue by ajlennon** [foundriesio/fiotest#14]
Hi,

I am using fiotest to do some initial manufacturing testing/setup that for example includes programming the NVM on some controller ICs. So I need to provide super-user privilege to the command that does that.

I don't see any kind of "user: root" option in the test-spec.yml for individual tests

What would you recommend as the best way to achieve the above?

Thanks!

Alex

**Comment by doanac** [comment]
In a dev environment you'll probably have password-less sudo so that you could have your command prefixed with `sudo`.

**Comment by ajlennon** [comment]
Yes but this isn't a dev environment. This is supply chain security. The boards are out in China. I need things testing and programming and I need a zero trust framework for this x

**Comment by doanac** [comment]
run-on-host uses ssh. I'm not sure there's a very secure way you could do that. Maybe you could mount enough of /dev into the container so that you could program it from there?

**Comment by ajlennon** [comment]
Haven't really got a perfect answer for this, but for my purposes the tool I need to use to do the programming can probably run setuid so I've takent this approach and will close this down :) Thanks !
