### ISSUE TITLE
Using fiotest as a production test tool

### ISSUE THREAD

**Issue by ajlennon** [foundriesio/fiotest#16]
Hi all,

So I've been working with fiotest for a while now as you know and obviously it's great!

Our use case - production & QA testing of hardware - might not be exactly what the majority of other users are doing but I think it's valid and would be useful to other board manufacturers so I wondered if I can bounce some thoughts and questions off here...

- I don't see any way with Foundries container management that I can disable a container programmatically. I think in terms of resource utilisation it would be helpful if I could run up a container and then at the end of that run use something to cause the container daemon to disable it. This way we could create images with a production test container that doesn't then run in the field. Is this possible and if not do you think it's worth supporting?

- Aside from the above, as the test container is currently always running whenever I update the image the tests re-run which isn't what I want to happen. For example I need to program the flash in some ICs and I only want to do this once. Currently I just `touch` a state file to check if I've done things and if it exists I skip running the test but it is a bit messy. 

- Further to this with our production testing I want to inform the technician what's happening which I'm thinking of doing via audio messages. Clearly I don't want to play audio messages in the field so again I need some way of managing this. I like the idea of individual tests in the `test-spec.yml` and those being reported to the cloud so I don't want to bundle everything into a single script as one test, which feels like I wouldn't be making good use of the fiotest tooling. But if I keep things separate then in each test block I have to check for a state file and create it and so forth which again is messy.

- So that leads me to wonder if there should be some kind of state where we only run tests 2, 3, 4 etc. on a conditional basis. So I could check if production testing had run on test 1 and then PASS without continuing on if that makes sense.

I am not sure I am expressing this clearly but I think this is a pretty reasonable use case here and I wondered if you have thoughts and/or advice?

I am **also** reminded of the saying that any application that reaches a certain level of complexity will end up with a scripting language embedded into it :-D

Cheers,

Alex

**Comment by doanac** [comment]
on container management: It sort of depends what you mean. Just pure "docker" container mgmt is possible by bind mounting the docker socket into a container. I think you are really asking about managing compose apps through our update system. One way you can manage this locally is via etc overrides for the aktualizr-lite sota.toml. Files are evaluated under `/etc/sota/conf.d` in order, so you could make a local file like:
```
# z-99-fiotest-override.yml (can override z-50-fioctl.toml)
[pacman]
compose_apps = "normal,list,plus,fiotest"
```

Then when fiotest completes, it could delete this file and then either restart aktualizr-lite or just stop the app depending on your use-case.

As per test-spec enhancements. I'm open to PRs if you have some  generically useful idea.

**Comment by ajlennon** [comment]
ok that's really interesting thanks. yes I I might take that approach then. I don't think for a production test I need to be changing this often, just as the last step of the test so the fiotest container doesn't run again. Thanks! (will close this)
